pkg_name=yup
pkg_origin=chefshafique
pkg_version="0.1.0"
pkg_scaffolding="core/scaffolding-go"
pkg_maintainer="The Chef Effortless Team <sales@chef.io>"
pkg_license=('Proprietary, All rights reserved')
pkg_bin_dirs=(bin)
pkg_source="https://github.com/mudash/YUP"
pkg_build_deps=(core/gcc core/go core/git core/make)